version: "3"
services:
  lbp-api-cloud-build:
    build:
      context: .
      dockerfile: dockerfiles/Ci.Dockerfile
    container_name: lbp-api-cloud-build
    tty: true
    user: www-data:www-data
    depends_on:
      - lbp-pg-cloud-build
    restart: "no"
    ports:
      - "1010:80"
    environment:
      APP_NAME: "Laravel API boilerplate"
      DB_HOST: "lbp-pg-cloud-build"
      DB_DATABASE: testing
      DB_PASSWORD: password
      DB_PORT: 5441
    #      MAIL_HOST: "lbp-mailpit"
    networks:
      lbp-network-cloud-build:
        ipv4_address: 10.10.1.1
    #    deploy:
    #      resources:
    #        limits:
    #          cpus: "2.0"
    #          memory: 500M
    extra_hosts:
      - host.docker.internal:host-gateway

  lbp-pg-cloud-build:
    image: postgres:15
    container_name: lbp-pg-cloud-build
    volumes:
      - lbp-pg-disk:/var/lib/postgres
    restart: always
    ports:
      - "5441:5432"
    expose:
      - "5441"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    networks:
      lbp-network-cloud-build:
        ipv4_address: 10.10.1.2

#  lbp-mailpit:
#    image: 'axllent/mailpit:latest'
#    container_name: lbp-mailpit
#    restart: always
#    networks:
#      lbp-network:
#        ipv4_address: 10.10.1.3

#  lbp-q:
#    build:
#      context: .
#      dockerfile: dockerfiles/QueueListener.Dockerfile
#    container_name: lbp-q
#    depends_on:
#      - lbp-api
#    volumes:
#      - .:/var/www/html
#    restart: unless-stopped
#    networks:
#      lbp-network:
#        ipv4_address: 10.10.1.4

#  lbp-0x:
#    build:
#      context: .
#      dockerfile: dockerfiles/0x.Dockerfile
#    container_name: lbp-0x
#    depends_on:
#      - lbp-api
#    volumes:
#      - .:/var/www/html
#    restart: always
#    networks:
#      lbp-network:
#        ipv4_address: 10.10.1.5

#  lbp-fe-app:
#    build:
#      context: .
#      dockerfile: dockerfiles/FeApp.Dockerfile
#    container_name: lbp-fe-app
#    ports:
#      - "1001:3000"
#    volumes:
#      - ./fe-app:/var/www/html
#      #- ./dockerfiles:/var/www/html/dockerfiles
#    restart: always
#    networks:
#      lbp-network:
#        ipv4_address: 10.10.1.6

# On-disk storage of DB data, when containers are stopped
volumes:
  lbp-pg-disk: { }

# Local network for services running using this docker-compose config
networks:
  lbp-network-cloud-build:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16
