steps:
  - name: 'docker'
    args: [ 'compose', '-f', 'ci-docker-compose.yml', 'up', '-d' ]
    id: settingDockerCompose
#  - name: 'docker/compose:latest'
#    script: "docker-compose -f ci-docker-compose.yml exec -T lbp-api composer install"
#    id: Installing dependencies
#  - name: 'docker/compose:latest'
#    script: "docker-compose -f ci-docker-compose.yml up -d"
#    id: CI_checks
#    waitFor:
#      - settingDockerCompose
#  - name: 'docker'
#    args: [ 'run', '-p', "5441:5432", 'lbp-api-cloud-build']
#    waitFor:
#      - settingDockerCompose
#    id: enabling-postgres-port
  - name: 'docker'
    args: [ 'compose', 'ps' ]
    waitFor:
      - settingDockerCompose
    #      - enabling-postgres-port
    id: logging
  - name: 'docker'
    args: [ 'compose', '-f', 'ci-docker-compose.yml', 'exec', 'lbp-api-cloud-build', '/bin/sh', '-c', 'php artisan migrate --force --seed']
    waitFor:
      - settingDockerCompose
#      - enabling-postgres-port
    id: running-migrations
  - name: 'docker'
    args: [ 'compose', 'exec', 'lbp-api-cloud-build', '/bin/sh', '-c', 'composer run ci']
    waitFor:
      - settingDockerCompose
      - running-migrations
    id: CI_checks
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - dockerfiles/GCP.Dockerfile
    waitFor:
      - CI_checks
      - settingDockerCompose
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    waitFor:
      - CI_checks
      - Build
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    waitFor:
      - CI_checks
      - Build
      - Push
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: v-team-isa2
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _TRIGGER_ID: 9a7a2ddf-efc4-440e-802a-f4144b779291
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - v-team-isa2
