version : "3"
services:
  lbp-api:
    build:
      context: .
      dockerfile: dockerfiles/Api.Dockerfile
    container_name: lbp-api
    depends_on:
      - lbp-pg
#      - lbp-es
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "1010:80"
    networks:
      lbp-network:
        ipv4_address: 10.10.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  lbp-pg:
    image: postgres:15
    container_name: lbp-pg
    volumes:
      - lbp-pg-disk:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    ports:
      - "5444:5432"
    networks:
      lbp-network:
        ipv4_address: 10.10.1.2

  lbp-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: lbp-mailpit
    restart: always
    ports:
      - "1011:8025"
    networks:
      lbp-network:
        ipv4_address: 10.10.1.3

  lbp-q:
    build:
      context: .
      dockerfile: dockerfiles/QueueListener.Dockerfile
    container_name: lbp-q
    depends_on:
      - lbp-api
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    networks:
      lbp-network:
        ipv4_address: 10.10.1.4

#  lbp-es:
#    image: elasticsearch:7.17.12
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    volumes:
#      - lbp-elasticsearch-disk:/usr/share/elasticsearch/data
#    networks:
#      lbp-network:
#        ipv4_address: 10.10.1.7

#  lbp-0x:
#    build:
#      context: .
#      dockerfile: dockerfiles/0x.Dockerfile
#    container_name: lbp-0x
#    depends_on:
#      - lbp-api
#    volumes:
#      - .:/var/www/html
#    restart: always
#    networks:
#      lbp-network:
#        ipv4_address: 10.10.1.5

#  lbp-fe-app:
#    build:
#      context: .
#      dockerfile: dockerfiles/FeApp.Dockerfile
#    container_name: lbp-fe-app
#    ports:
#      - "1001:3000"
#    volumes:
#      - ./fe-app:/var/www/html
#      #- ./dockerfiles:/var/www/html/dockerfiles
#    restart: always
#    networks:
#      lbp-network:
#        ipv4_address: 10.10.1.6

# On-disk storage of DB data, when containers are stopped
volumes:
  lbp-pg-disk: {}
  lbp-elasticsearch-disk:
    driver: local

# Local network for services running using this docker-compose config
networks:
  lbp-network:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16
