#!/bin/bash

chmod -R 777 storage bootstrap dockerfiles
chown -R www-data:www-data storage bootstrap dockerfiles

composer install --dev

php artisan migrate --force --seed
php artisan cache:clear

git config --global --add safe.directory /var/www/html
git config core.filemode false

# composer run pest

npm install
npm run build

apache2-foreground
