#!/bin/bash

#php artisan migrate --force --seed
#php artisan cache:clear

git config --global --add safe.directory /var/www/html
git config core.filemode false

# composer run pest

#npm install
#npm run build

apache2-foreground
