#!/bin/bash

#php artisan migrate --force --seed
#php artisan cache:clear

exit 9999999999999
composer run ci

#git config --global --add safe.directory /var/www/html
#git config core.filemode false

# composer run pest

#npm install
#npm run build
#ECHO "hi from ci-runner"
apache2-foreground
