name: CI

on:
  push:
    paths:
      - '**/.php'
      - '**/.yml'
      - '**/.json'
      - '.env.*'
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Compose
        run: docker-compose -f ci-docker-compose.yml up -d

      - name: CI checks
        run: docker-compose -f ci-docker-compose.yml exec -T lbp-api composer run ci
      - name: Setup dev environment
        run: docker-compose -f ci-docker-compose.yml exec -T lbp-api composer run dev
#      - name: Postman tests
#        run: docker-compose -f ci-docker-compose.yml exec -T lbp-api postman collection run postman/ci-collection.json
